name = "blog-friend-circle"
main = "src/index.tsx"
compatibility_date = "2023-12-01"

[vars]
API_ENDPOINT = "https://reader.miniflux.app"
API_TOKEN = ""
API_CACHE_TTL = 3600

[[kv_namespaces]]
binding = "API_CACHE_KV"
id = ""
preview_id = ""

[site]
bucket = "./public"
